packageExtensions:
  jest-environment-puppeteer@*:
    dependencies:
      jest-environment-node: ^26.2.0
      puppeteer: ^5.2.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
